language: cpp
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: false
    compiler: gcc-7
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-7
        - cmake
        - zlib1g-dev
        - libbz2-dev
        - libboost-dev
        - libgsl0-dev
    before_install:
    - "python3 --version || :"
    - "python --version || :"
    install: export CXX="g++-7"
    env:
    - LINK_TOOL="ldd"
    - DEPLOY_PATTERN="PureCLIP-*-linux64-{static,dynamic}.tar.gz"
  - os: osx
    osx_image: xcode9.2
    compiler: gcc-7
    before_install:
    - brew ls --versions
    - brew cask uninstall oclint
    - brew install gcc@7 gsl
    - brew install python || brew upgrade python
    - brew ls --versions
    - softwareupdate -l
    - "python3 --version || :"
    - "python --version || :"
    install: export CXX="g++-7"
    env:
    - LINK_TOOL="otool -L"
    - DEPLOY_PATTERN="PureCLIP-*-mac64.tar.gz"
script:
- ./util/pkg_check.py .
- mkdir -p build && cd build
- cmake ../src -DCMAKE_BUILD_TYPE=Release
- make VERBOSE=1
- "./pureclip --version"
- "./winextract --version"
- cmake . -DPKG_BUILD=1 -DSTATIC_BUILD=0
- make package
- "$LINK_TOOL pureclip || :"
- cmake . -DSTATIC_BUILD=1
- make package
- "$LINK_TOOL pureclip || :"
- ls -l
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: PiqTCnGo/oM8hkj+RwNj47F9KcD7E26tdQ1ZoJlRCoG7UK35dnjBDNsK7TwUp1jT9VQ7J7WckD3VjybLkeDL0D+4rHLkBJWtmViIU/cH1aGg1ltksjREgeB8El5FUVXQkd3RND02aPjqKsIdXlIEo7Z8wmQtTPhAQULqQLUBQzT5BAZq7mQJYPo3n2MpicwFQ6BrjCB0mB9+v/hgKaxEepED+rA5WhUG8djLrrwJ9X5sIdj13kwrbJwgBwdzGAKdoabZ/Sh7+nbK/YNilntnNxEdhD+WUhswOxEPuDuB+TsdTB96wrbAdrJctHIWIlDdgFiyn+gCpvvitTNG/JPZKa0z06NpqRcwqpvzPnAmNeQHw5F7qgvqB5zhoT2e9Xfvem4Rg1MwIhte+qDLCS6s7ySOvW+4+FCZXgSDHOC+wo4e40f382UmmbPctLplw04H9uEsYpF2vzVr1KNbCqigGetLz3OEHoSmjtrxpsgrMAcfvy1nmSK6vY1ESljD0zVVShHw4sVzOprE2jY93z49hQMZo9D0PbJRIh5arydMcdD4B7BKXS1/zM1XtWZRzNaJH8Rzw0jWPSLbtx7igfyZ/jOEdNIziS3KdacEJHEU5dkGoF7WovcAffZNxpWwQefry5Es8ox4MsI+A22jZ9YBIqqLK2+Lf3aOiP9Zn39ByI4=
  file_glob: True
  file: $DEPLOY_PATTERN
  on:
    tags: True
